=== artssassin/artssassin.github.io/nfts.dtd
<!ELEMENT NFTS (abstract?,NFT*)> 
<!ELEMENT abstract (#PCDATA)>
<!ELEMENT NFT (author+,date?,contract?,id?,collection?,web*,IPFS?,description?,comments*)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT date (year|(year,month)|(year,month,day))>
<!ELEMENT year (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT contract (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT collection (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!ELEMENT IPFS (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT comments (#PCDATA)>



<!ATTLIST NFT name CDATA #REQUIRED>
<!ATTLIST NFT blockchain (ethereum|polygon|solana) "ethereum">
<!ATTLIST NFT standard (ERC-1155|ERC-721) #IMPLIED>
<!ATTLIST NFT frozen (yes|no) #IMPLIED>
<!ATTLIST comments type (critic|opinion|news)  "critic" >

=== artssassin/artssassin.github.io/NFTSetxernalDTDexternalCSS.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="https://www.artssassin.com/nfts.css"?>


<!DOCTYPE NFTS SYSTEM "https://www.artssassin.com/nfts.dtd">



<NFTS> 

<abstract> Un ejemplo documento XML acerca de NFTs validado con una DTD etxerna y con CSS externo </abstract>

<NFT name="ART" blockchain="ethereum" frozen="no" standard="ERC-1155">
    
    
    <author>Artssassin</author> <date><year>2022</year><month>8</month><day>4</day></date> <contract>366352t6gshjsgdd</contract> <id> 3344</id> <collection>Filosofia</collection>
    <web> www.artssassin.com</web> <IPFS>ipfs/bafybeicndsidcgk5alt6eyzjpq4nzfxdxmlttwmw3fy5qgt3j64ab4sgpq/image.png</IPFS> 
   <description> Cómo nació la cita de NFTS</description> <comments type="critic" > El mejor</comments> 

</NFT>


<NFT name="ARTS" blockchain="ethereum" frozen="no">
    
    
    <author>Artssassin</author>  <collection>Filosofia</collection>
    <metadata>
        <title>Tema</title>
        <value>Filosofia</value>
    </metadata>
    
    <comments> Nice</comments>
    <comments type="opinion">Mi NFT favorito</comments>


</NFT>

</NFTS>
