<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="https://www.artssassin.com/nfts.css"?>

<!DOCTYPE NFTS [
<!ELEMENT NFTS (abstract?,NFT*)> 
<!ELEMENT abstract (#PCDATA)>
<!ELEMENT NFT (author+,date?,contract?,id?,collection?,web*,IPFS?,description?,metadata*,comments*)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT date (year|(year,month)|(year,month,day))>
<!ELEMENT year (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT contract (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT collection (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!ELEMENT IPFS (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT metadata (title,value)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT comments (#PCDATA)>



<!ATTLIST NFT name CDATA #REQUIRED>
<!ATTLIST NFT blockchain (ethereum|polygon|solana) "ethereum">
<!ATTLIST NFT standard (ERC-1155|ERC-721) #IMPLIED>
<!ATTLIST NFT frozen (yes|no) #IMPLIED>
<!ATTLIST comments type (critic|opinion|news)  "critic" >



]>
<NFTS>
    
<abstract> Un ejemplo documento XML acerca de NFTs validado con una DTD interna y con CSS externo</abstract>


<NFT name="The Foundation of NFT-XML" blockchain="ethereum" frozen="no">
    
    
    <author>Artssassin</author>  
    <contract>879438943</contract> 
    <collection>Filosofia</collection>
    <metadata>
        <title>Type</title>
        <value>Conceptual</value>
    </metadata>
    <metadata>
        <title>Topic</title>
        <value>MetaNFT</value>
    </metadata>
<comments>Conceptual, muy conceptual</comments>
    
    
</NFT>

<NFT name="Museo de Arte Total">
    <author>Artssassin</author>
    <collection>Registre</collection>
    <description>Un proyecto museográfico</description>
    <metadata>
        <title>Physical</title>
        <value>Yes</value>
      
    </metadata>
    <metadata>
        <title>Place</title>
        <value>MNAC</value>
        
    </metadata>
    
    <metadata>
        <title>Budget</title>
        <value>15.000</value>
    </metadata>
    <comments type="opinion">Hay que proporcionar más detalles</comments>
    <comments type="critic">Needs translation</comments>
</NFT>
    

</NFTS>
    
